<?php

namespace MadForWebs\TaskBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByFilter($userId = NULL)
    {

        $q = $this->createQueryBuilder('i')
            ->select('i')
            ->leftJoin('i.project', 'p')
            ->leftJoin('p.users', 'u');

        $q->andWhere('u.id = :user_id')
            ->setParameter ('user_id', $userId);

        return  $q->getQuery()->getResult();
    }
}
